version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack Indentional\Indentional.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*/**/*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 60xyS2iTNByJFsR6JCXlFcOiwhe+4FCjAjYGuymNUMRHEpPi1IUUQSff0zQC/FB3